### ISSUE TITLE
Update for notificato 1.1

### ISSUE THREAD

**Issue by jamesrgrinter** [rickpastoor/notificato-symfony#2]
Any chance of a build that pulls in wrep/notificato 1.1.* ?

I'd really like to use the MessageBuilder functionality, but notificato-symfony/1.0.* has (reasonably) got a dependency on 1.0.*.

**Comment by rickpastoor** [comment]
Could you open a PR? I'm happy to approve the bump. I'm not sure if I can find the time right now to fix this.

**Comment by tiois** [comment]
See my PR #3

**Comment by tiois** [comment]
The PR has been merged, this issue could be closed as well! :+1:

**Comment by rickpastoor** [comment]
Thanks man!
