### ISSUE TITLE
Fail to connect to ssl://gateway.push.apple.com:2195

### ISSUE THREAD

**Issue by MarzaLwm** [rickpastoor/notificato-symfony#4]
Hi,
these last days I've had problems with some notifications,
to send notifications the following exception began to appear:

`Error Exception: exception 'UnexpectedValueException' with message 'Failed to connect to ssl://gateway.push.apple.com:2195 with error #0 "Error before connecting, please check your certificate and passphrase combo and the given CA certificate if any.".' in vendor/wrep/notificato/src/Wrep/Notificato/Apns/SslSocket.php:109
Stack trace:
#0 /vendor/wrep/notificato/src/Wrep/Notificato/Apns/Gateway.php(89): Wrep\Notificato\Apns\SslSocket->connect()
#1 /vendor/wrep/notificato/src/Wrep/Notificato/Apns/Sender.php(123): Wrep\Notificato\Apns\Gateway->flush()
#2 /vendor/wrep/notificato/src/Wrep/Notificato/Notificato.php(85): Wrep\Notificato\Apns\Sender->flush(NULL)
#3 controlNotificaciones.php(701): Wrep\Notificato\Notificato->flush()
#4 controlNotificaciones.php(137): controlNotificaciones::notificarIosDevices(1, Array, Object(Incidencia), Object(Monolog\Logger), Object(appDevDebugProjectContainer))
#5 Command/notificarIncidenciaCommand.php(63): controlNotificaciones::notificarIncidencia(Object(Incidencia), Object(Partido), Object(appDevDebugProjectContainer))
#6 /vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php(257): Command\notificarIncidenciaCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(882): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(195): Symfony\Component\Console\Application->doRunCommand(Object(\Command\notificarIncidenciaCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(96): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /vendor/symfony/symfony/src/Symfony/Component/Console/Application.php(126): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /opt/sdp/entelfutbolclub/www/sf2/app/console(27): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#12 {main}`

I should mention that all the logic of the notifications is executed from a command of symfony,
the command and notification works fine during longer than a month and now sometimes triggered the exception and sometimes function well.

the notifications are about football matchs, for example goals and start of a match, so if are two matchs in the same time the command 
that triggers the notifications is executed two times. once for each match 

Suspect that the trouble can be related with trigger from a command many times.
but i dont understand why not happened before

can anyone give me a clue
I do not understand why not happen before

**Comment by mac-cain13** [comment]
Thanks for using this project and posting your issue here.

The first thing you should check is if the certificate you use is still valid. The certificates Apple creates for push notifications are valid for 1 year, you need to create a new certificate and start using the new one before the expiry date or else Apple will reject your connection as your see happen here.

If you're sure this is not the problem it could be that you open too many connections to APNS at a time that could also cause this error, but I have to say that I think that is not a very likely scenario unless you're opening 100 of connections at the same time.

**Comment by MarzaLwm** [comment]
Hi, 
thanks for the answer
the certificate is still valid this, should not be the problem.

one command running send many notifications and at the same time (2 minutes interval) should not run more than 8 command to send different notifications

do you think that is too many connections?

**Comment by mac-cain13** [comment]
It's better to use just one connection, but a small amount of connections does not necessarily have to be a problem.

Does sending a push never work or does it only fail sometimes?

Things to check:
- Is the certificate still valid? (You already answered that with yes)
- Are you using the correct certificate for the correct environment? (Sandbox/production)
- Is the passphrase for the certificate correct?
- Do you use a CA certificate? [Apples WWDR expired](https://developer.apple.com/support/certificates/expiration/) lately and you should have the correct root certs on the server that is sending the push
- Can you manage to send one push from your development machine? If so what is the difference with production?

**Comment by MarzaLwm** [comment]
Hi, sorry  for not replying before, I was dedicated to other tasks.
I had activated an error log to monitor the situation and the truth has not failed again.
apparently failed 4 or 5 days and until now has not happened again.

thanks for attention, help and tips
I think we can give the issue closed even though I do not know what happened
regards

**Comment by mac-cain13** [comment]
Thanks for the update!
