### ISSUE TITLE
symfony 3 support

### ISSUE THREAD

**Issue by rbaarsma** [rickpastoor/notificato-symfony#5]
Currently not able to use this bundle with symfony 3, because it has a requirement: `symfony/symfony: 2.*`

**Comment by mac-cain13** [comment]
I've tagged the release so this is now available on packagist!

**Comment by rbaarsma** [comment]
Quick work! Thanks :)

**Comment by rickpastoor** [comment]
Thanks @mac-cain13, speedy as always ;) and thanks @rbaarsma for your work!
